import type { KeyboardGroup, KeyboardKey } from '@/types/element';
import { getShapesByCategory } from '@/lib/shapes';

function shapeKeys(category: '2d-solid' | '2d-dashed' | '3d'): KeyboardKey[] {
  return getShapesByCategory(category).map((s) => ({
    label: s.label,
    type: 'shape' as const,
    content: s.id,
    hint: s.hint,
  }));
}

export const KEYBOARD_GROUPS: KeyboardGroup[] = [
  {
    title: 'Numbrid',
    short: '123',
    keys: [
      { label: '0', type: 'number', content: '0' },
      { label: '1', type: 'number', content: '1' },
      { label: '2', type: 'number', content: '2' },
      { label: '3', type: 'number', content: '3' },
      { label: '4', type: 'number', content: '4' },
      { label: '5', type: 'number', content: '5' },
      { label: '6', type: 'number', content: '6' },
      { label: '7', type: 'number', content: '7' },
      { label: '8', type: 'number', content: '8' },
      { label: '9', type: 'number', content: '9' },
      { label: '.', type: 'number', content: '.' },
      { label: ',', type: 'number', content: ',' },
    ],
  },
  {
    title: 'Tehted',
    short: '±',
    keys: [
      { label: '+', type: 'operator', content: '+', hint: 'pluss' },
      { label: '−', type: 'operator', content: '−', hint: 'miinus' },
      { label: '×', type: 'operator', content: '×', hint: 'korrutamine' },
      { label: '·', type: 'operator', content: '·', hint: 'korrutamine punkt' },
      { label: '÷', type: 'operator', content: '÷', hint: 'jagamine' },
      { label: '/', type: 'operator', content: '/', hint: 'jagamine kriips' },
      { label: '±', type: 'operator', content: '±', hint: 'pluss-miinus' },
      { label: '∓', type: 'operator', content: '∓', hint: 'miinus-pluss' },
      { label: '!', type: 'operator', content: '!', hint: 'faktoriaal' },
      { label: '%', type: 'operator', content: '%', hint: 'protsent' },
      { label: '°', type: 'operator', content: '°', hint: 'kraad' },
      { label: '′', type: 'operator', content: '′', hint: 'minut' },
    ],
  },
  {
    title: 'Võrdlus',
    short: '=',
    keys: [
      { label: '=', type: 'operator', content: '=' },
      { label: '≠', type: 'operator', content: '≠', hint: 'ei ole võrdne' },
      { label: '≈', type: 'operator', content: '≈', hint: 'ligikaudu' },
      { label: '≡', type: 'operator', content: '≡', hint: 'identne' },
      { label: '<', type: 'operator', content: '<' },
      { label: '>', type: 'operator', content: '>' },
      { label: '≤', type: 'operator', content: '≤', hint: 'väiksem või võrdne' },
      { label: '≥', type: 'operator', content: '≥', hint: 'suurem või võrdne' },
      { label: '≪', type: 'operator', content: '≪', hint: 'palju väiksem' },
      { label: '≫', type: 'operator', content: '≫', hint: 'palju suurem' },
      { label: '∝', type: 'operator', content: '∝', hint: 'proportsionaalne' },
      { label: '∞', type: 'operator', content: '∞', hint: 'lõpmatus' },
    ],
  },
  {
    title: 'Sulud',
    short: '( )',
    keys: [
      { label: '(', type: 'paren', content: '(' },
      { label: ')', type: 'paren', content: ')' },
      { label: '[', type: 'paren', content: '[' },
      { label: ']', type: 'paren', content: ']' },
      { label: '{', type: 'paren', content: '{' },
      { label: '}', type: 'paren', content: '}' },
      { label: '⟨', type: 'paren', content: '⟨', hint: 'nurksulg vasak' },
      { label: '⟩', type: 'paren', content: '⟩', hint: 'nurksulg parem' },
      { label: '|', type: 'paren', content: '|', hint: 'absoluutväärtus' },
      { label: '‖', type: 'paren', content: '‖', hint: 'norm' },
    ],
  },
  {
    title: 'Muutujad',
    short: 'x',
    keys: [
      { label: 'x', type: 'variable', content: 'x' },
      { label: 'y', type: 'variable', content: 'y' },
      { label: 'z', type: 'variable', content: 'z' },
      { label: 'a', type: 'variable', content: 'a' },
      { label: 'b', type: 'variable', content: 'b' },
      { label: 'c', type: 'variable', content: 'c' },
      { label: 'k', type: 'variable', content: 'k' },
      { label: 'n', type: 'variable', content: 'n' },
      { label: 't', type: 'variable', content: 't' },
      { label: 'i', type: 'variable', content: 'i' },
      { label: 'e', type: 'variable', content: 'e', hint: 'Euleri arv' },
      { label: 'π', type: 'variable', content: 'π', hint: 'pii' },
    ],
  },
  {
    title: 'Kreeka — väiketähed',
    short: 'α',
    keys: [
      { label: 'α', type: 'variable', content: 'α', hint: 'alfa' },
      { label: 'β', type: 'variable', content: 'β', hint: 'beeta' },
      { label: 'γ', type: 'variable', content: 'γ', hint: 'gamma' },
      { label: 'δ', type: 'variable', content: 'δ', hint: 'delta' },
      { label: 'ε', type: 'variable', content: 'ε', hint: 'epsilon' },
      { label: 'ζ', type: 'variable', content: 'ζ', hint: 'zeeta' },
      { label: 'η', type: 'variable', content: 'η', hint: 'eeta' },
      { label: 'θ', type: 'variable', content: 'θ', hint: 'teeta' },
      { label: 'λ', type: 'variable', content: 'λ', hint: 'lambda' },
      { label: 'μ', type: 'variable', content: 'μ', hint: 'müü' },
      { label: 'ξ', type: 'variable', content: 'ξ', hint: 'ksii' },
      { label: 'ρ', type: 'variable', content: 'ρ', hint: 'roo' },
      { label: 'σ', type: 'variable', content: 'σ', hint: 'sigma' },
      { label: 'τ', type: 'variable', content: 'τ', hint: 'tau' },
      { label: 'φ', type: 'variable', content: 'φ', hint: 'fii' },
      { label: 'χ', type: 'variable', content: 'χ', hint: 'khii' },
      { label: 'ψ', type: 'variable', content: 'ψ', hint: 'psii' },
      { label: 'ω', type: 'variable', content: 'ω', hint: 'oomega' },
    ],
  },
  {
    title: 'Kreeka — suurtähed',
    short: 'Ω',
    keys: [
      { label: 'Γ', type: 'variable', content: 'Γ', hint: 'Gamma' },
      { label: 'Δ', type: 'variable', content: 'Δ', hint: 'Delta' },
      { label: 'Θ', type: 'variable', content: 'Θ', hint: 'Teeta' },
      { label: 'Λ', type: 'variable', content: 'Λ', hint: 'Lambda' },
      { label: 'Ξ', type: 'variable', content: 'Ξ', hint: 'Ksii' },
      { label: 'Π', type: 'variable', content: 'Π', hint: 'Pii' },
      { label: 'Σ', type: 'variable', content: 'Σ', hint: 'Sigma' },
      { label: 'Φ', type: 'variable', content: 'Φ', hint: 'Fii' },
      { label: 'Ψ', type: 'variable', content: 'Ψ', hint: 'Psii' },
      { label: 'Ω', type: 'variable', content: 'Ω', hint: 'Oomega' },
    ],
  },
  {
    title: 'Trigonomeetria',
    short: 'sin',
    keys: [
      { label: 'sin', type: 'function', content: 'sin', hint: 'siinus' },
      { label: 'cos', type: 'function', content: 'cos', hint: 'koosinus' },
      { label: 'tan', type: 'function', content: 'tan', hint: 'tangens' },
      { label: 'cot', type: 'function', content: 'cot', hint: 'kotangens' },
      { label: 'sec', type: 'function', content: 'sec', hint: 'seekans' },
      { label: 'csc', type: 'function', content: 'csc', hint: 'koseekans' },
      { label: 'arcsin', type: 'function', content: 'arcsin' },
      { label: 'arccos', type: 'function', content: 'arccos' },
      { label: 'arctan', type: 'function', content: 'arctan' },
      { label: 'sinh', type: 'function', content: 'sinh', hint: 'hüperboolne siinus' },
      { label: 'cosh', type: 'function', content: 'cosh' },
      { label: 'tanh', type: 'function', content: 'tanh' },
    ],
  },
  {
    title: 'Logaritmid ja piir',
    short: 'ln',
    keys: [
      { label: 'log', type: 'function', content: 'log' },
      { label: 'ln', type: 'function', content: 'ln', hint: 'naturaallogaritm' },
      { label: 'lg', type: 'function', content: 'lg', hint: 'kümnendlogaritm' },
      { label: 'exp', type: 'function', content: 'exp' },
      { label: 'lim', type: 'function', content: 'lim', hint: 'piirväärtus' },
      { label: 'max', type: 'function', content: 'max' },
      { label: 'min', type: 'function', content: 'min' },
      { label: 'sup', type: 'function', content: 'sup' },
      { label: 'inf', type: 'function', content: 'inf' },
      { label: 'det', type: 'function', content: 'det' },
      { label: 'mod', type: 'function', content: 'mod' },
      { label: 'gcd', type: 'function', content: 'gcd', hint: 'SÜT' },
    ],
  },
  {
    title: 'Integraalid ja summad',
    short: '∑',
    keys: [
      { label: '∑', type: 'operator', content: '∑', hint: 'summa' },
      { label: '∏', type: 'operator', content: '∏', hint: 'korrutis' },
      { label: '∫', type: 'operator', content: '∫', hint: 'integraal' },
      { label: '∬', type: 'operator', content: '∬', hint: 'kahekordne integraal' },
      { label: '∭', type: 'operator', content: '∭', hint: 'kolmekordne integraal' },
      { label: '∮', type: 'operator', content: '∮', hint: 'kontuurintegraal' },
      { label: '∂', type: 'operator', content: '∂', hint: 'osatuletis' },
      { label: '∇', type: 'operator', content: '∇', hint: 'nabla' },
      { label: 'd', type: 'variable', content: 'd', hint: 'diferentsiaal' },
      { label: 'Δ', type: 'variable', content: 'Δ', hint: 'muut' },
    ],
  },
  {
    title: 'Hulgateooria',
    short: '∈',
    keys: [
      { label: '∈', type: 'operator', content: '∈', hint: 'kuulub' },
      { label: '∉', type: 'operator', content: '∉', hint: 'ei kuulu' },
      { label: '⊂', type: 'operator', content: '⊂', hint: 'alamhulk' },
      { label: '⊆', type: 'operator', content: '⊆' },
      { label: '⊃', type: 'operator', content: '⊃' },
      { label: '⊇', type: 'operator', content: '⊇' },
      { label: '∪', type: 'operator', content: '∪', hint: 'ühend' },
      { label: '∩', type: 'operator', content: '∩', hint: 'ühisosa' },
      { label: '∖', type: 'operator', content: '∖', hint: 'vahe' },
      { label: '∅', type: 'operator', content: '∅', hint: 'tühi hulk' },
      { label: 'ℕ', type: 'variable', content: 'ℕ', hint: 'naturaalarvud' },
      { label: 'ℤ', type: 'variable', content: 'ℤ', hint: 'täisarvud' },
      { label: 'ℚ', type: 'variable', content: 'ℚ', hint: 'ratsionaalarvud' },
      { label: 'ℝ', type: 'variable', content: 'ℝ', hint: 'reaalarvud' },
      { label: 'ℂ', type: 'variable', content: 'ℂ', hint: 'kompleksarvud' },
    ],
  },
  {
    title: 'Loogika',
    short: '∀',
    keys: [
      { label: '¬', type: 'operator', content: '¬', hint: 'eitus' },
      { label: '∧', type: 'operator', content: '∧', hint: 'ja' },
      { label: '∨', type: 'operator', content: '∨', hint: 'või' },
      { label: '⊕', type: 'operator', content: '⊕', hint: 'välistav või' },
      { label: '→', type: 'operator', content: '→', hint: 'implikatsioon' },
      { label: '↔', type: 'operator', content: '↔', hint: 'ekvivalents' },
      { label: '⇒', type: 'operator', content: '⇒' },
      { label: '⇔', type: 'operator', content: '⇔' },
      { label: '∀', type: 'operator', content: '∀', hint: 'iga' },
      { label: '∃', type: 'operator', content: '∃', hint: 'leidub' },
      { label: '∄', type: 'operator', content: '∄', hint: 'ei leidu' },
      { label: '⊢', type: 'operator', content: '⊢' },
    ],
  },
  {
    title: 'Nooled',
    short: '→',
    keys: [
      { label: '→', type: 'operator', content: '→' },
      { label: '←', type: 'operator', content: '←' },
      { label: '↔', type: 'operator', content: '↔' },
      { label: '↑', type: 'operator', content: '↑' },
      { label: '↓', type: 'operator', content: '↓' },
      { label: '⇒', type: 'operator', content: '⇒' },
      { label: '⇐', type: 'operator', content: '⇐' },
      { label: '⇔', type: 'operator', content: '⇔' },
      { label: '↦', type: 'operator', content: '↦', hint: 'kuvab' },
      { label: '⟶', type: 'operator', content: '⟶' },
    ],
  },
  {
    title: 'Geomeetria',
    short: '∠',
    keys: [
      { label: '∠', type: 'operator', content: '∠', hint: 'nurk' },
      { label: '∡', type: 'operator', content: '∡', hint: 'suunatud nurk' },
      { label: '⊥', type: 'operator', content: '⊥', hint: 'ristseis' },
      { label: '∥', type: 'operator', content: '∥', hint: 'paralleelne' },
      { label: '△', type: 'operator', content: '△', hint: 'kolmnurk' },
      { label: '□', type: 'operator', content: '□', hint: 'ruut' },
      { label: '○', type: 'operator', content: '○', hint: 'ring' },
      { label: '⌒', type: 'operator', content: '⌒', hint: 'kaar' },
      { label: '≅', type: 'operator', content: '≅', hint: 'sarnane' },
      { label: '∼', type: 'operator', content: '∼', hint: 'sarnane' },
    ],
  },
  {
    title: 'Struktuurid',
    short: '√',
    keys: [
      { label: 'a⁄b', type: 'fraction', content: { numerator: 'a', denominator: 'b' }, hint: 'Murd' },
      { label: 'x²', type: 'power', content: { base: 'x', exponent: '2' }, hint: 'Aste (ruut)' },
      { label: 'xⁿ', type: 'power', content: { base: 'x', exponent: 'n' }, hint: 'Aste (n)' },
      { label: '√', type: 'sqrt', content: '□', hint: 'Ruutjuur' },
      { label: '∛', type: 'sqrt', content: '∛□', hint: 'Kuupjuur' },
      { label: '—', type: 'line', content: '', hint: 'Joon (vabalt venitav)' },
      { label: 'Aa', type: 'text', content: 'tekst', hint: 'Silt (tekst)' },
    ],
  },
  {
    title: 'Kujundid 2D',
    short: '△',
    keys: shapeKeys('2d-solid'),
  },
  {
    title: 'Kujundid 2D punktiir',
    short: '◇',
    keys: shapeKeys('2d-dashed'),
  },
  {
    title: 'Kujundid 3D',
    short: '◨',
    keys: shapeKeys('3d'),
  },
];

export function flattenKeys(): KeyboardKey[] {
  return KEYBOARD_GROUPS.flatMap((g) => g.keys);
}

export function keyId(k: KeyboardKey): string {
  const c = typeof k.content === 'string' ? k.content : JSON.stringify(k.content);
  return `${k.type}::${c}`;
}
